# -*- coding: utf-8 -*-
"""project aisa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yxqh69RFrMW7jaxJvwaPmKo30iDn3omx
"""

import pandas as pd
import matplotlib.pyplot as plt

import pandas as pd

file_path = "/AISA_Financial_Analysis (1).xlsx"

# cek nama sheet
xls = pd.ExcelFile(file_path)
print(xls.sheet_names)

df = pd.read_excel(file_path, sheet_name="Raw Data (Excel-Ready)")
df.head()

df = pd.read_excel(file_path, sheet_name="Raw Data (Excel-Ready)", skiprows=1)
df.head()

df.info()

df['Tahun'] = pd.to_numeric(df['Tahun'], errors='coerce')
df = df.dropna(subset=['Tahun'])
df['Tahun'] = df['Tahun'].astype(int)
df.info()
display(df.head())

df = df.copy()

df['Tahun'] = pd.to_numeric(df['Tahun'], errors='coerce')
df = df.dropna(subset=['Tahun'])

df['Tahun'] = df['Tahun'].astype(int)

df['profit_margin'] = df['Net Profit'] / df['Revenue']
df['roe'] = df['Net Profit'] / df['Total Equity']
df['roa'] = df['Net Profit'] / df['Total Assets']

plt.plot(df['Tahun'], df['Revenue'], marker='o', label='Revenue')
plt.plot(df['Tahun'], df['Net Profit'], marker='o', label='Net Profit')
plt.legend()
plt.title("Revenue vs Net Profit")
plt.show()

plt.plot(df['Tahun'], df['profit_margin'], marker='o')
plt.title("Profit Margin Trend")
plt.show()